name: "Publish to PyPI"

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    pypi-publish:
      name: upload release to PyPI
      runs-on: ubuntu-latest
      permissions:
        # This permission is needed for private repositories.
        contents: read
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
      steps:
        - uses: actions/checkout@v3

        - uses: pdm-project/setup-pdm@v3

        - name: "sync from upstream"
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            make sync

        - name: Publish package distributions to PyPI
          run: pdm publish
